version: "3.1"

services:
  musicdb:
    image: mysql:8.0.17
    ports:
#TODO: change to env variables 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'music_test'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - webnet
    secrets:
       - db_root_password


  web:
    image: musicdbserver
    ports:
      - 2020:2020
    depends_on:
      - musicdb
    env_file:
      - musicdb.env
    #volume bound to path in the host. Use :Z to share this volume (And preventing SELinux to complain about permissions)
    volumes:
      - ${MUSIC_DB_CONFIG_VOL}:/app_config:Z
    networks:
      - webnet
    links:
      - "musicdb:musicdb"
      
secrets:
   db_root_password:
     file: ${MUSIC_DB_PSSWD_FILE}
     
networks:
  webnet:  

volumes:
  mysqldb:
  
