version: "3.1"
services:
  web:
    image: musicdbserver
    ports:
      - "2020:2020"
    depends_on:
      - musicdb
    env_file:
      - musicdb.env
    #volume bound to path in the host. Use :Z to share this volume (And preventing SELinux to complain about permissions)
    volumes:
      - ${MUSIC_DB_CONFIG_VOL}:/app_config:Z
    networks:
      - webnet
      
  musicdb:
     image: mysql:8.0.17
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_DATABASE: 'music_test'
       MYSQL_USER: 'root'
#      Password for root access
       MYSQL_ROOT_PASSWORD: 'nevermore'
       port: 3306
#    Volumes where our data will be persisted
     volumes:
       - mysqldb:/var/lib/mysql
     networks:
      - webnet
     
# 
#   dbadmin:    
#     image: adminer    
#     ports:      
#       - "8181:8080"
networks:
  webnet:  

volumes:
  mysqldb:
  
