version: "3"
services:
  web:
    image: musicdbserver
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "2020:2020"
    networks:
      - webnet
networks:
  webnet:
