version: "3.1"

services:
  musicdb:
    image: mysql:8.0.17
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'music_test'
#TODO: change to env variables
      MYSQL_USER: 'root'
#     Password for root access
      MYSQL_ROOT_PASSWORD: 'nevermore'
#    Volumes where our data will be persisted
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - webnet


  web:
    image: musicdbserver
    ports:
#TODO: change to env variables 
      - 2020:2020
    depends_on:
      - musicdb
    env_file:
      - musicdb.env
    #volume bound to path in the host. Use :Z to share this volume (And preventing SELinux to complain about permissions)
    volumes:
      - ${MUSIC_DB_CONFIG_VOL}:/app_config:Z
    networks:
      - webnet
    links:
      - "musicdb:musicdb"
      

     
networks:
  webnet:  

volumes:
  mysqldb:
  
