version: "3.1"

services:
  musicdb:
    image: mysql:8.0.17
    ports:
      - "${DATABASE_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    env_file:
      - ${MUSIC_DB_ENV_FILE}
    volumes:
      - mysqldb:/var/lib/mysql:Z
    networks:
      - webnet
    secrets:
      - db_root_password


  web:
    env_file:
      - ${MUSIC_DB_ENV_FILE}
    image: godlessendeavor/musicdbserver
    ports:
      - ${MUSICDB_PORT}:${MUSICDB_PORT}
    depends_on:
      - musicdb
    #volume bound to path in the host. Use :Z to share this volume (And preventing SELinux to complain about permissions)
    volumes:
      - ${MUSIC_DB_CONFIG_VOL}:/app_config:Z
    networks:
      - webnet
    links:
      - "musicdb:musicdb"
      
secrets:
   db_root_password:
     file: ${MUSIC_DB_PSSWD_FILE}
     
networks:
  webnet:  

volumes:
  mysqldb:
  
