apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1
  name: music-service
contexts:
- context:
    cluster: music-service
    user: cluster-admin
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: cluster-admin
  user: {}
