apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE music (Id        INT NOT NULL,
                        groupName VARCHAR(256) DEFAULT '',
                        copy      VARCHAR(256) DEFAULT '',
                        country   VARCHAR(256) DEFAULT '',
                        loc       VARCHAR(256) DEFAULT '',
                        mark      VARCHAR(256) DEFAULT '',
                        review    BLOB         DEFAULT '',
                        style     VARCHAR(256) DEFAULT '',
                        title     VARCHAR(256) DEFAULT '',
                        type      VARCHAR(256) DEFAULT '',
                        year      INT          DEFAULT 0,
                        PRIMARY KEY (Id));
    CREATE TABLE favorites (Id          INT NOT NULL,
                            disc_id     INT NOT NULL,
                            score       FLOAT        DEFAULT 0,
                            track_no    INT          DEFAULT 0,
                            track_title VARCHAR(256) DEFAULT '',
                            file_name   VARCHAR(256) DEFAULT '',
                            type        VARCHAR(256) DEFAULT '',
                            PRIMARY KEY (Id),
                            FOREIGN KEY (disc_id) REFERENCES music(Id));
