apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE music (Id        INT          NOT NULL AUTO_INCREMENT,
                        band      VARCHAR(256) DEFAULT '',
                        copy      VARCHAR(256) DEFAULT '',
                        country   VARCHAR(256) DEFAULT '',
                        score     VARCHAR(256) DEFAULT '',
                        review    BLOB,
                        style     VARCHAR(256) DEFAULT '',
                        title     VARCHAR(256) DEFAULT '',
                        type      VARCHAR(256) DEFAULT '',
                        year      INT          DEFAULT 0,
                        PRIMARY KEY (Id));
    CREATE TABLE favorites (Id           INT NOT NULL AUTO_INCREMENT,
                            album_id     INT NOT NULL,
                            score        FLOAT        DEFAULT 0,
                            track_number INT          DEFAULT 0,
                            track_title  VARCHAR(256) DEFAULT '',
                            file_name    VARCHAR(256) DEFAULT '',
                            type         VARCHAR(256) DEFAULT '',
                            PRIMARY KEY (Id),
                            FOREIGN KEY (album_id) REFERENCES music(Id));
