apiVersion: v1
kind: Service
metadata:
  labels:
    io.musicdb.service: web
  name: web
spec:
  type: NodePort
  ports:
  - name: "2020"
    nodePort: 32020
    port: 2020
    targetPort: 2020
  selector:
    io.musicdb.service: web
status:
  loadBalancer: {}
