apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.musicdb.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.musicdb.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.musicdb.network/webnet: "true"
        io.musicdb.service: web
    spec:
      restartPolicy: Always
      containers:
        - name: web
          image: docker.io/godlessendeavor/musicdbserver
          envFrom:
          - configMapRef:
              name: musicdb-config
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: dbrootpassword
                 key: mysql-root-password         
          ports:
          - containerPort: 2020
status: {}
