swagger: "2.0"

info:
  title: "Music Database Server"
  version: "1.0"
#  license:
#    name: Apache 2.0
#    url: http://www.apache.org/licenses/LICENSE-2.0.html


schemes:
 - http
paths:             
  /music/albums: #make sure to not leave trailing slashes in the path or Flask will redirect the response to the URL with trailing slash 
      get:
        summary: 'Fetch albums from the music database'
        parameters:
        - in: query
          name: quantity
          type: integer
          required: false
          description: Number of random albums to get. If not indicated it will return all albums.
        - in: query
          name: album_id
          type: integer
          required: false
          description: Id of album to get. If this parameter is set the parameter quantity will not be checked.
        tags:
        - public
        operationId: api.albums.get_albums
        responses:
          '200':
              description: Fetch album(s) from the music database
              schema:
                 type: array
                 items:
                    $ref: '#/definitions/album'   
      post:
         summary: Creates a new album.
         consumes:
           - application/json
         parameters:
           - in: body
             name: album
             description: The album to create.
             required: true
             schema:
                $ref: '#/definitions/album'
         tags:
           - public
         operationId: api.albums.create_album
         responses:
           '200':
              description: OK           
                 
      put:
         summary: Updates an album.
         consumes:
           - application/json
         parameters:
           - in: body
             name: album
             description: The album to update.
             required: true
             schema:
               $ref: '#/definitions/album'
         tags:
           - public
         operationId: api.albums.update_album
         responses:
           '200':
              description: OK    
              
      delete:
         summary: Deletes an album.
         consumes:
           - application/json
         parameters:
           - in: query
             name: album_id
             type: integer             
             required: true
             description: The album id to delete.
         tags:
           - public
         operationId: api.albums.delete_album
         responses:
           '200':
              description: OK     
              
  /music/fav_songs: #make sure to not leave trailing slashes in the path or Flask will redirect the response to the URL with trailing slash 
      get:
        summary: 'Fetch random songs from the favorites database'
        parameters:
        - in: query
          name: quantity
          type: integer
          required: false
          description: Number of favorite songs to get. If not indicated it will return 1 song (if there is at least one song matching the score criteria).
        - in: query
          name: score
          type: integer
          required: false
          description: Minimum score of the favorite songs to get. If not indicated minimum is 0.
        tags:
        - public
        operationId: api.songs.get_songs
        responses:
          '200':
              description: Fetch random songs from the favorites database
              schema:
                 type: object
                 properties:
                    songs:
                       type: array
                       items:
                          $ref: '#/definitions/song'   
      post:
         summary: Creates a new favorite song.
         consumes:
           - application/json
         parameters:
           - in: body
             name: song
             description: The song to create.
             required: true
             schema:
               $ref: '#/definitions/song'
         tags:
           - public
         operationId: api.songs.create_song
         responses:
           '200':
              description: OK           
                 
      put:
         summary: Updates a favorite song.
         consumes:
           - application/json
         parameters:
           - in: body
             name: song
             description: The song to update.
             required: true
             schema:
               $ref: '#/definitions/song'
         tags:
           - public
         operationId: api.songs.update_song
         responses:
           '200':
              description: OK    
              
      delete:
         summary: Deletes a favorite song.
         consumes:
           - application/json
         parameters:
           - in: query
             name: song_id
             type: integer             
             required: true
             description: The song id to delete.
         tags:
           - public
         operationId: api.songs.delete_song
         responses:
           '200':
              description: OK       

                
                
tags:
- name: public
  description: Operations available to regular developers
#- name: admins
#  description: Secured Admin-only calls

definitions:
  album:
    type: object
    properties:
      id:           { type: string }
      band:         { type: string }
      title:        { type: string }
      style:        { type: string }
      year:         { type: string }
      country:      { type: string }
      path:         { type: string }
      type:         { type: string }
      score:        { type: string }
      review:       { type: string }
      copy:         { type: string }
   
      
  song:
    type: object
    properties:
      id:           { type: string }
      disc_id:      { type: string }
      title:        { type: string }
      file_name:    { type: string }
      track_number: { type: string }
      score:        { type: string }
      type:         { type: string }
   
      


      
      
      
      
      
             